### ISSUE TITLE
打包出现这个问题？UnhandledPromiseRejectionWarning: Unhandled promise rejection

### ISSUE THREAD

**Issue by shenzheniapps** [vortesnail/react-ts-quick-starter#2]
(node:63957) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:63957) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by vortesnail** [comment]
这个错误是你 Promise 没写好

**Comment by shenzheniapps** [comment]
大神， 你好：
我是按照你的教程一步一步跟的 ，还没有自己敲代码， 但是能运行起来在本地， 打包的时候 就出现这个问题了， 我在怀疑是不是版本兼容的问题，但是 这个错误 我不知道怎么去查，请赐教， 谢谢啦

**Comment by vortesnail** [comment]
> This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). 

这个错误就是你的异步函数没有写 .catch()，可能的确是版本问题，你可以看看你是做到了哪一步写了 Promise ，然后加上这句话试试。

**Comment by shenzheniapps** [comment]
![image](https://user-images.githubusercontent.com/13235552/100964238-28f34c80-3563-11eb-96d1-6dbf6bd27de7.png)
暂时还没有写自己的code 呢 这是我的错误信息，大佬看看

**Comment by vortesnail** [comment]
terser-webpack-plugin这个插件版本回退到4.00版本看看。

**Comment by shenzheniapps** [comment]
@vortesnail  十分感谢 ！！！"terser-webpack-plugin": "^4.0.0",  用这个版本没有 成功打包了 ，再次谢谢！

**Comment by shenzheniapps** [comment]
你好大佬：
![image](https://user-images.githubusercontent.com/13235552/102103382-e33e5a00-3e67-11eb-9b80-da44ec837c34.png)
项目中用到Material-ui的 UI库，但是在使用style.js的时候 ，VS Code 遇到这个报错，但是可以编译成功，请问怎么解决 ，十分感谢
