### ISSUE TITLE
打出来的包貌似没法用

### ISSUE THREAD

**Issue by Gavin-ZYX** [vortesnail/react-ts-quick-starter#6]
试了master和另一个分支的项目，clone下来install后。执行npm run build之后，打出来的包是没法用的，打开是个空白页面。
不知是我使用的问题，还是其他人没用过这个打包，没看到别人提这个。

**Comment by Gavin-ZYX** [comment]
start跑起来的项目没有任何问题

**Comment by vortesnail** [comment]
> start跑起来的项目没有任何问题

你可能得先了解一下如何在本地 nginx 上部署一个服务。你直接打开 html 文件是没有用。

**Comment by Gavin-ZYX** [comment]
应该是因为我的改动引起的
